version: "3"

services:
  mysql:
    image: bitnami/mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/bitnami/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  mysql_data:
    driver: local
